spring:
  # Settings
  config:
    activate:
      on-profile: oauth
# OAUTH2
oauth2:
  kakao:
    client_id: ${OAUTH2_KAKAO_CLIENT_ID}
    redirect_url: "http://localhost:9090/oauth-redirect-kakao"
  naver:
    client_id: ${OAUTH2_NAVER_CLIENT_ID}
    client_secret: ${OAUTH2_NAVER_CLIENT_SECRET}
    redirect_url: "http://localhost:9090/oauth-redirect-naver"
  google:
    client_id: ${OAUTH2_GOOGLE_CLIENT_ID}
    client_secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
    redirect_url: "http://localhost:9090/oauth-redirect-google"