# Server-Port
server:
  port: 80

spring:
  # PROFILES
  profiles:
    include: [mail, oauth]

# JWT
auth:
  jwt:
    issuer: ${JWT_ISSUER}
    secret: ${JWT_SECRET}
    accessTokenExpirationHour: ${JWT_ACCESS_TOKEN_EXPIRATION_HOUR}
    refreshTokenExpirationHour: ${JWT_REFRESH_TOKEN_EXPIRATION_HOUR}

# SLACK
slack:
  bot-token: ${SLACK_BOT_TOKEN}
  channel: ${SLACK_CHANNEL}

# AWS S3
accessKey: ${AWS_S3_ACCESS_KEY}
secretKey: ${AWS_S3_SECRET_KEY}
bucket: ${AWS_S3_BUCKET}
dir: ${AWS_S3_DIR}
region: ${AWS_S3_REGION}
