name: CI Test Bingo

on:
  pull_request:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    services:
      redis:
        image: redis:latest
        ports:
          - 6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set-up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "corretto"

      - name: Add permission before build
        run: chmod +x gradlew

      - name: Build with gradle
        run: ./gradlew build

      # 추후 test workflow 추가